baidu_appid: Your_App_ID
baidu_apikey: Your_Api_Key
baidu_secretkey: Your_Secret_Key
appreciate:
Real_CUGAN:
ai_detect:
img_to_music:
remove_bg:
cartoonization:
APIList: []
usingAPI: 1
baidu_translate:
  id: null
  key: null
youdao_translate:
  id: null
  key: null
