concise_mode: false
max_fold: 500
def_prompt: ""
def_negativeprompt: EasyNegative, nsfw, lowres, bad anatomy, bad hands, text,
  error, missing fingers, extra digit, fewer digits, cropped, worst quality, low
  quality, normal quality, jpeg artifacts, signature, watermark, username,
  blurry
debug: false